### ISSUE TITLE
Error running storybook after doing a build

### ISSUE THREAD

**Issue by jamesscottbrown** [Greater-London-Authority/ldn-viz-tools#38]
After doing a build locally, trying to run storybook locally with ` npm run storybook -w apps/docs` results in an error:

```
WARN 🚨 Unable to index ../../packages/maps/dist/Introduction.mdx,../../packages/maps/src/lib/Introduction.mdx:                                     
WARN   Error: You have two component docs pages with the same name Maps/Introduction:Docs. Use `<Meta of={} name="Other Name">` to distinguish them.
WARN     at StoryIndexGenerator.chooseDuplicate (C:\Users\JScott-Brown\code\ldn-viz-tools\node_modules\@storybook\core-server\dist\index.js:17:2235)
WARN     at C:\Users\JScott-Brown\code\ldn-viz-tools\node_modules\@storybook\core-server\dist\index.js:17:3666                                      
WARN     at Array.forEach (<anonymous>)                                                                                                             
WARN     at StoryIndexGenerator.getIndex (C:\Users\JScott-Brown\code\ldn-viz-tools\node_modules\@storybook\core-server\dist\index.js:17:3573)       
WARN     at async C:\Users\JScott-Brown\code\ldn-viz-tools\node_modules\@storybook\core-server\dist\index.js:35:3776    
```

**Comment by ChrisKnightLDN** [comment]
Need to be more explicit in apps/docs/.storybook/main.ts as it seems to be finding the duplicate story in the dist folder...
